[package]
name = "nlp100ex2020r2"
version = "0.1.0"
authors = ["Shuntaro Yada <contact@shuntaroy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
